### ISSUE TITLE
Change center.disc to a rectangle shape and fill the highlighted area

### ISSUE THREAD

**Issue by ghost** [ibrierley/Snap.svg.FreeTransform#4]
Could you give me any pointers in regards to updating the ' ft.handles.center.disc' so that instead of being a circle in the middle of an element with the plugin applied, it becomes a rectangle shape which matches the size of the selected element? My hope is that then you could drag and move an element anywhere inside the selected area?

**Comment by ibrierley** [comment]
It's not entirely clear what you are meaning. Do you mean you want a bounding box drag or something ?
What happens if the object and handlers are rotated, do you want a rotated drag area ?

Best normally is to put an example on a jsfiddle to try and highlight the issue. I would also use the dev branch currently, as it resolves a few other issues that may be useful.

**Comment by ghost** [comment]
Sorry, I'll knock something up - essentially I'm trying to
